// =============================================================================
// horizon.js — the measured horizon profile: the app's novel capability. A
// site's real skyline as a 36-point azimuth→altitude table (every 10°), the
// altitude of the treeline/obstruction blocking each direction. sampleAt()
// interpolates it at any azimuth (wrapping cleanly past north), and isAbove()
// is the "above MY horizon" primitive every visibility answer stands on.
//
// 100% headless-testable — deliberately built and proven before any device
// sensor work. Profiles persist per site (Step 7); for now a single working
// profile lives in localStorage under horizon.profile.
// =============================================================================

export const STEP = 10;          // degrees of azimuth per row
export const N = 360 / STEP;     // 36 rows
const KEY = 'horizon.profile';

const clampAlt = (a) => Math.max(0, Math.min(90, a));
const norm360 = (az) => ((az % 360) + 360) % 360;

/**
 * A horizon profile. `altitudes[i]` is the obstruction altitude (degrees) at
 * azimuth `i·STEP`, i = 0..35 (0 = due north, clockwise through E/S/W).
 * @param altitudes optional 36-length array; defaults to a flat 0° horizon.
 */
export function makeHorizon(altitudes) {
  const a = new Array(N).fill(0);
  if (Array.isArray(altitudes)) {
    for (let i = 0; i < N; i++) if (Number.isFinite(altitudes[i])) a[i] = clampAlt(altitudes[i]);
  }
  return { step: STEP, altitudes: a };
}

/** The azimuth (degrees) of row `i`. */
export function azForIndex(i) { return ((i % N) + N) % N * STEP; }

/** Nearest row index to an azimuth. */
export function indexForAz(az) { return Math.round(norm360(az) / STEP) % N; }

/** Set row `i`'s altitude (mutates), clamped to [0,90]. Returns the profile. */
export function setAltitudeAt(profile, i, altitude) {
  profile.altitudes[((i % N) + N) % N] = clampAlt(altitude);
  return profile;
}

/**
 * Interpolated obstruction altitude at any azimuth. Linear between the two
 * bracketing rows, wrapping across the 350°→0° seam so due north is continuous.
 */
export function sampleAt(profile, az) {
  const a = profile.altitudes;
  const x = norm360(az) / STEP;      // position in row units
  const i0 = Math.floor(x) % N;
  const i1 = (i0 + 1) % N;
  const frac = x - Math.floor(x);
  return a[i0] + frac * (a[i1] - a[i0]);
}

/**
 * Is a point at (azimuth, altitude) above the measured horizon? The core
 * "above MY horizon" test. Optionally require clearing the treeline by a margin.
 */
export function isAbove(profile, az, altitude, margin = 0) {
  return altitude > sampleAt(profile, az) + margin;
}

/** Highest obstruction anywhere (degrees). */
export function maxAltitude(profile) { return Math.max(...profile.altitudes); }

/** True if nothing is obstructed (flat 0° horizon). */
export function isFlat(profile) { return profile.altitudes.every((a) => a === 0); }

// --- Stellarium import / export ---------------------------------------------
// Stellarium's polygonal-landscape horizon list is plain text: one
// "azimuth altitude" pair per line (degrees; azimuth 0=N clockwise), blanks and
// #-comments ignored. We export the 36 rows plus a closing 360° point so the
// polygon is explicitly closed; we import ANY such list and resample onto the
// 36-row grid, so a denser or offset file still lands cleanly on our model.

/** Serialize a profile to a Stellarium horizon list. */
export function toStellarium(profile) {
  const lines = ['# Horizon profile — azimuth altitude (deg), 0=N clockwise',
    '# Generated by Horizon Planner'];
  for (let i = 0; i < N; i++) lines.push(`${azForIndex(i)} ${round2(profile.altitudes[i])}`);
  lines.push(`360 ${round2(profile.altitudes[0])}`); // close the loop
  return lines.join('\n') + '\n';
}

/**
 * Parse a Stellarium horizon list into a 36-row profile, resampling by linear
 * interpolation. Throws if no usable "az alt" pairs are found.
 */
export function fromStellarium(text) {
  const pts = [];
  for (const raw of String(text).split(/\r?\n/)) {
    const line = raw.split('#')[0].trim();
    if (!line) continue;
    const m = line.split(/[\s,]+/).map(Number);
    if (m.length >= 2 && Number.isFinite(m[0]) && Number.isFinite(m[1])) {
      pts.push({ az: norm360(m[0]), alt: clampAlt(m[1]) });
    }
  }
  if (!pts.length) throw new Error('no azimuth/altitude pairs found');
  pts.sort((p, q) => p.az - q.az);
  return makeHorizon(resample(pts));
}

// Sample arbitrary (az,alt) points onto the 36-row grid. Wraps around 360 by
// treating the first point as also sitting at az+360.
function resample(pts) {
  const wrapped = [...pts, { az: pts[0].az + 360, alt: pts[0].alt }];
  const out = new Array(N).fill(0);
  for (let i = 0; i < N; i++) {
    const az = azForIndex(i);
    out[i] = interp(wrapped, az) ?? interp(wrapped, az + 360) ?? 0;
  }
  return out;
}
function interp(pts, az) {
  for (let k = 0; k < pts.length - 1; k++) {
    const a = pts[k], b = pts[k + 1];
    if (az >= a.az && az <= b.az) {
      if (b.az === a.az) return a.alt;
      return a.alt + ((az - a.az) / (b.az - a.az)) * (b.alt - a.alt);
    }
  }
  return null;
}

const round2 = (x) => Math.round(x * 100) / 100;

// --- Persistence (single working profile; per-site arrives in Step 7) -------
export function loadHorizon() {
  try {
    const v = JSON.parse(localStorage.getItem(KEY) || 'null');
    if (v && Array.isArray(v.altitudes)) return makeHorizon(v.altitudes);
  } catch { /* fall through */ }
  return makeHorizon();
}
export function saveHorizon(profile) {
  try { localStorage.setItem(KEY, JSON.stringify({ altitudes: profile.altitudes })); }
  catch { /* private mode */ }
}
